# Generated by Django 4.2.7 on 2024-01-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grading_content_type",
            field=models.CharField(
                help_text="The MIMEType of the test picture", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="grading_picture",
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
