# Generated by Django 4.2.7 on 2024-01-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_grading_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grading_material",
            field=models.CharField(
                blank=True,
                choices=[("test", "テスト"), ("essay", "作文"), ("speech", "スピーチ")],
                max_length=10,
                null=True,
            ),
        ),
    ]
