# Generated by Django 4.2.7 on 2024-01-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_grading_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grading_material_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="grading_material_grade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
