# Generated by Django 4.2.7 on 2024-01-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_grading_material_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="grading_content_type",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="grading_material",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="grading_material_comment",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="grading_material_grade",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="grading_picture",
        ),
    ]
