# Generated by Django 4.2.7 on 2023-12-27 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "月曜日"),
                            ("Tuesday", "火曜日"),
                            ("Wednesday", "水曜日"),
                            ("Thursday", "木曜日"),
                            ("Friday", "金曜日"),
                            ("Saturday", "土曜日"),
                            ("Sunday", "日曜日"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "spot",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                ("text", models.TextField(null=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("sky", "水色"),
                            ("green", "緑色"),
                            ("yellow", "黄色"),
                            ("purple", "紫色"),
                            ("pink", "ピンク色"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("time", models.CharField(max_length=12, null=True)),
                ("picture", models.BinaryField(editable=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        help_text="The MIMEType of the file", max_length=256, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("sky", "水色"),
                            ("green", "緑色"),
                            ("yellow", "黄色"),
                            ("purple", "紫色"),
                            ("pink", "ピンク色"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Japanese_Basic_1", "日本語初級１"),
                            ("Japanese_Basic_2", "日本語初級２"),
                            ("Japanese_Basic_3", "日本語初級３"),
                            ("Japanese_Basic_4", "日本語初級４"),
                            ("Japanese_Advanced_1", "日本語中級１"),
                            ("Japanese_Advanced_2", "日本語中級２"),
                            ("Japanese_Advanced_3", "日本語中級３"),
                            ("Japanese_Advanced_4", "日本語中級４"),
                            ("Japanese_Expert_1", "日本語上級１"),
                            ("Japanese_Expert_2", "日本語上級２"),
                            ("Japanese_Expert_3", "日本語上級３"),
                            ("Japanese_Expert_4", "日本語上級４"),
                            ("Math", "数学"),
                            ("Science", "科学等"),
                            ("Social_Studies", "社会"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("picture", models.BinaryField(editable=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        help_text="The MIMEType of the file", max_length=256, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipationCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.schedule",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LateAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("late", models.PositiveIntegerField(default=0)),
                ("late_reason", models.TextField(null=True)),
                (
                    "absence",
                    models.CharField(choices=[("yes", "はい")], max_length=3, null=True),
                ),
                ("absence_reason", models.TextField(null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("order", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "lesson",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
