# Generated by Django 4.2.7 on 2023-12-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "月曜日"),
                    ("Tuesday", "火曜日"),
                    ("Wednesday", "水曜日"),
                    ("Thursday", "木曜日"),
                    ("Friday", "金曜日"),
                    ("Saturday", "土曜日"),
                    ("Sunday", "日曜日"),
                ],
                max_length=90,
                null=True,
            ),
        ),
    ]
