# Generated by Django 4.2.7 on 2024-01-03 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_alter_lesson_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grading_picture", models.BinaryField(editable=True, null=True)),
                (
                    "grading_content_type",
                    models.CharField(
                        help_text="The MIMEType of the test picture",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "grading_material",
                    models.CharField(
                        blank=True,
                        choices=[("test", "テスト"), ("essay", "作文"), ("speech", "スピーチ")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "grading_material_grade",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("grading_material_comment", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
