# Generated by Django 4.2.7 on 2024-01-11 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_nametodolists_todolist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="name_to_do_lists",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.nametodolists",
            ),
        ),
    ]
