# Generated by Django 4.2.7 on 2024-01-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_todolist_name_to_do_lists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grading",
            name="grading_material",
            field=models.CharField(
                blank=True,
                choices=[("test", "Test"), ("essay", "Essay"), ("speech", "Speech")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lateabsence",
            name="absence",
            field=models.CharField(choices=[("yes", "Yes")], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="color",
            field=models.CharField(
                choices=[
                    ("sky", "Light Blue"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=90,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="category",
            field=models.CharField(
                choices=[
                    ("Japanese_Basic_1", "Japanese Basic 1"),
                    ("Japanese_Basic_2", "Japanese Basic 2"),
                    ("Japanese_Basic_3", "Japanese Basic 3"),
                    ("Japanese_Basic_4", "Japanese Basic 4"),
                    ("Japanese_Advanced_1", "Japanese Advanced 1"),
                    ("Japanese_Advanced_2", "Japanese Advanced 2"),
                    ("Japanese_Advanced_3", "Japanese Advanced 3"),
                    ("Japanese_Advanced_4", "Japanese Advanced 4"),
                    ("Japanese_Expert_1", "Japanese Expert 1"),
                    ("Japanese_Expert_2", "Japanese Expert 2"),
                    ("Japanese_Expert_3", "Japanese Expert 3"),
                    ("Japanese_Expert_4", "Japanese Expert 4"),
                    ("Math", "Math"),
                    ("Science", "Science"),
                    ("Social_Studies", "Social Studies"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="color",
            field=models.CharField(
                choices=[
                    ("sky", "Sky Blue"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
